version: '2'
services:
  sqlserver:
    image: microsoft/mssql-server-linux:2017-latest
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Lucas16061997@
      MSSQL_PID: Developer
    ports:
      - '1433:1433'

  uowback:
    image: uowback:latest
    hostname: 'uowback-end'
    network_mode: "host"
    ports:
      - '8081:8081'
    depends_on:
     - "sqlserver"